AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 instance for CDK deployment with required IAM permissions'

Parameters:
  InstanceType:
    Type: String
    Default: t3.medium
    Description: EC2 instance type
    AllowedValues:
      - t3.small
  
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair for SSH access (optional)
    Default: ''

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

Conditions:
  HasKeyPair: !Not [!Equals [!Ref KeyPairName, '']]

Resources:
  # IAM Role for EC2 with required permissions
  CDKDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-CDKDeploymentRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
      Policies:
        - PolicyName: CDKDeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:GetRole
                  - iam:PassRole
                  - iam:TagRole
                  - iam:CreatePolicy
                  - iam:DeletePolicy
                  - iam:GetPolicy
                  - iam:GetPolicyVersion
                  - iam:ListPolicyVersions
                Resource: '*'

  # Instance Profile
  CDKDeploymentInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref CDKDeploymentRole

  # Security Group
  CDKDeploymentSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for CDK deployment EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH access
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-SG'

  # EC2 Instance
  CDKDeploymentInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: !Ref CDKDeploymentInstanceProfile
      SecurityGroupIds:
        - !Ref CDKDeploymentSecurityGroup
      KeyName: !If [HasKeyPair, !Ref KeyPairName, !Ref 'AWS::NoValue']
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-CDK-Deployment'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          
          # Log output
          exec > >(tee /var/log/user-data.log)
          exec 2>&1
          
          echo "Installing required packages for CDK deployment..."
          
          # Update system
          yum update -y
          
          # Install Node.js 18
          curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
          yum install -y nodejs
          
          # Install Python and dependencies
          yum install -y python3 python3-pip git unzip
          
          # Install AWS CDK
          npm install -g aws-cdk
          
          # Install AWS CLI v2 (if not already installed)
          if ! command -v aws &> /dev/null; then
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              ./aws/install
              rm -rf awscliv2.zip aws/
          fi
          
          echo "Package installation complete! Ready for git clone and deployment."

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref CDKDeploymentInstance
  
  PublicIP:
    Description: Public IP address
    Value: !GetAtt CDKDeploymentInstance.PublicIp
  
  SSHCommand:
    Description: SSH command to connect
    Value: !Sub 'ssh -i your-key.pem ec2-user@${CDKDeploymentInstance.PublicIp}'
  
  DeploymentCommand:
    Description: Command to run after SSH
    Value: './deploy.sh'
